version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/MicroMachines.Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/MicroMachines.Basket.API/Dockerfile

volumes:
  catalogdb_data:
