version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - catalogdb_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  sqldata:
    container_name: sqldata
    environment:     
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PswD12345678
    restart: always
    ports:
      - "1401:1433" 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
      - CatalogApiClient=http://catalog.api
      - TransferApiClient=http://transfer.api
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"

  shopping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=sqldata;Database=OrderDb;User=sa;Password=PswD12345678;"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "8002:80"

  transfer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ConnectionStrings:TransferConnectionString=Server=sqldata;Database=TransferDb;User=sa;Password=PswD12345678;"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "8003:80"

