version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis
  
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/MicroMachines.Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/MicroMachines.Basket.API/Dockerfile

  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Services/Shopping/MicroMachines.Shopping.API/Dockerfile

volumes:
  catalogdb_data:

