version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/MicroMachines.Catalog.API/Dockerfile

volumes:
  catalogdb_data: